services:
  frontend:
    build: 
      context: ./frontend
      dockerfile: Dockerfile.dev
    container_name: frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - backend
    # environment:
    #   - NEXT_PUBLIC_API_URL=http://localhost:8000 
    networks:
      - laws_network

  backend:
    build:
      context: ./backend
    container_name: backend
    ports:
      - "8000:8000"
    volumes: 
      - ./backend:/app 
      - ./data/backend-artefacts:/app/artefacts 
    environment:
      MONGO_URI: mongodb://mongodb:27017
      MONGO_DB_NAME: nigerian_laws_db
      MONGO_COLLECTION_NAME: "raw_documents"
      GITHUB_PERSONAL_ACCESS_TOKEN: ${GITHUB_PERSONAL_ACCESS_TOKEN}
      # OLLAMA_BASE_URL: http://ollama:11434
      # OLLAMA_MODEL: qwen3:0.6b 
    depends_on:
      - mongodb
      # - ollama 
      # - ollama-setup
    networks:
      - laws_network


  mongodb:
    image: mongo:latest
    container_name: mongo_Db
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - laws_network

  mongo-express:
    image: mongo-express:latest
    container_name: laws_mongo_express
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_SERVER: mongodb
      ME_CONFIG_MONGODB_PORT: 27017
      ME_CONFIG_BASICAUTH_USERNAME: admin 
      ME_CONFIG_BASICAUTH_PASSWORD: pass
      ME_CONFIG_MONGODB_URL: mongodb://mongodb:27017/ 
    depends_on:
      - mongodb
    networks:
      - laws_network

volumes:
  mongo_data:

networks:
  laws_network:
    driver: bridge