services:
  frontend:
    build: 
      context: ./frontend
      dockerfile: Dockerfile.dev
    container_name: frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    # depends_on:
    #   - backend
    # environment:
    #   - NEXT_PUBLIC_API_URL=http://localhost:8000 
    # networks:
    #   - 